#!/bin/bash
#SBATCH --partition=gpu
#SBATCH --gres=gpu:v100:1
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=16GB
#SBATCH --time=48:00:00
#SBATCH --account=ppanda_1734


module load gcc/13.3.0
module load cuda/12.4.0
module load conda

conda init bash
source ~/.bashrc

conda activate ee599

jupyter nbconvert --to notebook --execute squeezenet.ipynb --output squeezenet_output.ipynb